#!/bin/sh
devilspie &
tint2 &
#xcompmgr -c -t-5 -l-5 -r4.2 -o.55 &
(sleep 1s && exec ~/.conky/pekwm/conky_start_pekwm.sh) 
#cairo-compmgr -n &
#xcompmgr -c -C -r 2 -l 0 -t 0
#urxvt &
#firefox &
#pidgin &
#thunar &
